# Load antigen for bundling
source ~/.config/zsh/antigen.zsh

POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=
POWERLEVEL9K_VCS_BRANCH_ICON=

alias e="emacs -nw"
alias ls="exa"

antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme bhilburn/powerlevel9k powerlevel9k

antigen apply
