# Configure Plug.kak and plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/fzf.kak"
plug "alexherbo2/surround.kak"
plug "alexherbo2/auto-pairs.kak"
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}

# Always show number lines
add-highlighter global/ number-lines

#
# Mappings
#

# Enter Surround Mode
map -docstring 'surround mode' global normal q ': surround-mode<ret>'

#
# Hooks
#

# Yank to the system clipboard (`y` only)
hook global NormalKey y %{
    nop %sh{
        encoded=$(printf %s "$kak_main_reg_dquote" | base64 | tr -d '\n')
        printf "\e]52;c;%s\e\\" "$encoded" >/dev/tty
    }
}

# javascript
hook global BufSetOption filetype=javascript %{
    # Format javascript files with Prettier
    set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"

    # Format buffer after exiting insert mode
    hook buffer ModeChange pop:insert:normal format
}
