# [language.javascript]
# filetypes = ["javascript"]
# roots = [".flowconfig", "package.json"]
# command = "flow"
# args = ["lsp"]

[language.tsx]
filetypes = ["typescript", "javascript"]
roots = [".git"]
command = "typescript-language-server"
args = ["--stdio"]
[language.tsx.settings]
maxTsServerMemory="4096"

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

# [language.typescript]
# filetypes = ["typescript", "javascript"]
# roots = [".git"]
# command = "deno"
# args = ["lsp"]
# 
# [language.typescript.settings.deno]
# enable = true
# lint = true

# Semantic tokens support
# See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens
# for the default list of tokens and modifiers.
# However, many language servers implement their own values.
# Make sure to check the output of `lsp-capabilities` and each server's documentation and source code as well.
# Examples:
# - TypeScript: https://github.com/microsoft/vscode-languageserver-node/blob/2645fb54ea1e764aff71dee0ecc8aceff3aabf56/client/src/common/semanticTokens.ts#L58
# - Rust Analyzer: https://github.com/rust-analyzer/rust-analyzer/blob/f6da603c7fe56c19a275dc7bab1f30fe1ad39707/crates/ide/src/syntax_highlighting.rs#L42
[semantic_tokens]
faces = [
    {face="documentation", token="comment", modifiers=["documentation"]},
    {face="comment", token="comment"},
    {face="function", token="function"},
    {face="keyword", token="keyword"},
    {face="module", token="namespace"},
    {face="operator", token="operator"},
    {face="string", token="string"},
    {face="type", token="type"},
    {face="default+d", token="variable", modifiers=["readonly"]},
    {face="default+d", token="variable", modifiers=["constant"]},
    {face="variable", token="variable"},
]
